### ISSUE TITLE
Unlimited Device creation on the same number!

### ISSUE THREAD

**Issue by Aboraad748** [sejator/wabot#1]
## the user can create unlimited devices and sessions on the same number, by changing (No Whatsapp) in Device creation form.
this two devices are connected on the same whatsapp number:
https://pasteboard.co/73NomrdZ1sTW.png

**Comment by sejator** [comment]
Thank you for the report, I have updated this problem [https://github.com/sejator/wabot/commit/958566bb6904f46948b59c9e904189b6db655af3](https://github.com/sejator/wabot/commit/958566bb6904f46948b59c9e904189b6db655af3)

**Comment by Aboraad748** [comment]
Thank you for your support and excellent work 💯
