### ISSUE TITLE
A request for adding an api endpoint.

### ISSUE THREAD

**Issue by Aboraad748** [sejator/wabot#3]
Hello Sejator,
I was wondering if you could add an api endpoint to get the WhatsApp QR code string as response.

**Comment by sejator** [comment]
Looks like it can, maybe I'll update in the next few days

**Comment by Aboraad748** [comment]
Thank you for your efforts.

**Comment by sejator** [comment]
API device endpoint has been added [https://github.com/sejator/wabot/commit/ad2efa56368c4e21673353ff8c21afc2506de7fb](https://github.com/sejator/wabot/commit/ad2efa56368c4e21673353ff8c21afc2506de7fb)

**Comment by Aboraad748** [comment]
Thank you very much.
