### ISSUE TITLE
Improvement: sent message status

### ISSUE THREAD

**Issue by Aboraad748** [sejator/wabot#4]
Hello Sejator,
is there anyway to know if a sent message is read or not, maybe also handling status like message delivered.

Thank you for your efforts.

**Comment by sejator** [comment]
This feature is not yet available, but you can check the *messages* field *read* table for contents 1-4.

[https://github.com/sejator/wabot/blob/fc051fd52d1ca21352bafbbd3cb412e5381a7a54/prisma/schema.prisma#L154](https://github.com/sejator/wabot/blob/fc051fd52d1ca21352bafbbd3cb412e5381a7a54/prisma/schema.prisma#L154)
