### ISSUE TITLE
Issue: automatic reply

### ISSUE THREAD

**Issue by sinau-programming** [sejator/wabot#5]
Automatic reply sending reply when we delete one of our message. It also sending auto reply in group chat when we delete some chat even though  isGroup column value is 0
![IMG_20240310_101700](https://github.com/sejator/wabot/assets/111106972/994e05e7-30fb-41fb-9f49-9abf5b0eeb1a)

**Comment by sejator** [comment]
What do you mean by deleting private and group messages and sending a notification to the bot? or where to send it?
