### ISSUE TITLE
incoming message tidak  masuk ke database mysql

### ISSUE THREAD

**Issue by azkamuliainternational** [sejator/wabot#6]
sudah mengaktifkan pesan masuk, tetapi table message tidak ada
apakah harus isi webhook, dan diisi dengan url apa? 
![image](https://github.com/sejator/wabot/assets/64679833/2825aae6-0303-4c08-8478-fda8bd29f65f)

**Comment by sejator** [comment]
Untuk pesan yang masuk ke **wabot** memang tidak di simpan ke database.

Kemudian untuk url webhook disini adalah url yang nanti akan menerima pesan yang di teruskan **wabot** ke url tersebut.

Alurnya ketika ada pesan masuk, setingan dapatkan pesan masuk aktif, url webhook di isi. Maka pesan akan di teruskan ke url tersebut. Untuk dokumentasinya memang belum lengkap. Nanti kalau udah senggang insya Allah saya update lagi.
